flasher:
    translate: true
    options:
        timeout: 2500
    presets:
        success:
            title: 'Succ√®s'
        error:
            title: 'Erreur'
        warning:
            title: 'Attention'
        info:
            title: 'Information'
