framework:
    rate_limiter:
        password_reset_ip:
            policy: 'sliding_window'
            limit: 5
            interval: '1 hour'
        password_reset_email:
            policy: 'sliding_window'
            limit: 5
            interval: '1 hour'

when@test:
    framework:
        rate_limiter:
            password_reset_ip:
                policy: 'sliding_window'
                limit: 1000
                interval: '1 hour'
            password_reset_email:
                policy: 'sliding_window'
                limit: 1000
                interval: '1 hour'
